import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Phase 0: generate TWO throwaway Base Sepolia wallets (buyer + seller) and write .env.
// Footgun guard: refuses to overwrite an existing .env (it may hold funded keys) unless --force; with
// --force, an existing ANTHROPIC_API_KEY / CLAUDE_CODE_OAUTH_TOKEN line is carried over.
const ROOT = dirname(dirname(fileURLToPath(import.meta.url))); // repo root
const ENV = join(ROOT, ".env");

if (existsSync(ENV) && !process.argv.includes("--force")) {
  console.error(`${ENV} already exists: refusing to overwrite (it may hold funded wallet keys). Pass --force to really regenerate.`);
  process.exit(1);
}
const prev = existsSync(ENV) ? readFileSync(ENV, "utf8") : "";
const keep = (name: string) => prev.match(new RegExp(`^${name}=(.*)$`, "m"))?.[1] ?? "";

const buyerKey = generatePrivateKey();
const buyer = privateKeyToAccount(buyerKey);
const sellerKey = generatePrivateKey();
const seller = privateKeyToAccount(sellerKey);

const env = [
  "# ---- Phase 0 (testnet, throwaway) — generated by gen-wallets.ts ----",
  "# Claude auth: an Anthropic API key (default). See .env.example for the subscription opt-in.",
  `ANTHROPIC_API_KEY=${keep("ANTHROPIC_API_KEY")}`,
  ...(keep("CLAUDE_CODE_OAUTH_TOKEN") ? [`CLAUDE_CODE_OAUTH_TOKEN=${keep("CLAUDE_CODE_OAUTH_TOKEN")}`] : []),
  "",
  "# Buyer = the citizen's funded wallet. FUND THIS with USDC: https://faucet.circle.com (Base Sepolia)",
  `BUYER_PRIVATE_KEY=${buyerKey}`,
  "",
  "# Seller = the shop's payout address (key kept for reference only; receiving needs no key).",
  `SELLER_ADDRESS=${seller.address}`,
  `SELLER_PRIVATE_KEY=${sellerKey}`,
  "",
  "SHOP_URL=http://localhost:4031",
  "GOOD=bread",
  "PRICE=$0.01",
  "TICKS=3",
  "",
].join("\n");

writeFileSync(ENV, env);
console.log("wrote", ENV);
console.log("BUYER  (fund this with USDC):", buyer.address);
console.log("SELLER (receives payments):  ", seller.address);
console.log("\nNext:");
console.log("  1. Put your Anthropic API key into .env (ANTHROPIC_API_KEY=)");
console.log("  2. Fund the BUYER at https://faucet.circle.com (Base Sepolia, 20 USDC)");
console.log("  3. `npm run shop`  (terminal A)   then   `npm run citizen0`  (terminal B)");
